# Generated by Django 5.0.4 on 2024-06-19 18:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='article/%Y_%m_%d/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название новости')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новости')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=4056, verbose_name='Отзыв')),
                ('status', models.CharField(choices=[('0', 'На рассмотрении'), ('1', 'Одобрено'), ('2', 'Отказано')], default=0, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('imageA', models.ImageField(blank=True, upload_to='works/%Y/%m/%d/', verbose_name='Изображение на верхнем плане')),
                ('imageB', models.ImageField(blank=True, upload_to='works/%Y/%m/%d/', verbose_name='Изображение на нижнем плане')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorksTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='WorksTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название выполненой задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
