# Generated by Django 5.0.4 on 2024-06-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contents.workstags', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='workstasks',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.works'),
        ),
    ]
